export const services = [
  {
    id: 'ai-chatbots',
    icon: 'MessageSquare',
    title: 'AI Chatbot Setup',
    shortDescription: 'Custom GPT chatbot trained on your content, FAQs, and documents.',
    roi: 'Handle 70% of customer inquiries automatically',
    features: [
      '24/7 automated customer support',
      'Lead qualification and capture',
      'Appointment scheduling integration',
      'Multi-language support',
      'Custom personality and tone',
    ],
    tools: ['ChatGPT', 'Botpress', 'ManyChat'],
    deliverables: [
      'Fully trained chatbot widget',
      'Custom persona and knowledge base',
      'CRM and calendar integrations',
      'Analytics dashboard',
    ],
    image: 'https://images.unsplash.com/photo-1762330470070-249e7c23c8c0?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2NjZ8MHwxfHNlYXJjaHwxfHxjaGF0Ym90JTIwaW50ZXJmYWNlfGVufDB8fHx8MTc2NDIxNDMyNXww&ixlib=rb-4.1.0&q=85',
    useCases: ['Support automation', 'Lead qualification', 'Appointment booking', 'FAQ responses'],
  },
  {
    id: 'lead-qualification',
    icon: 'Filter',
    title: 'Lead Qualification Workflows',
    shortDescription: 'Automated lead scoring, qualification questions, and intelligent routing.',
    roi: 'Increase qualified leads by 40% and reduce sales time by 60%',
    features: [
      'Automatic lead scoring and tagging',
      'Smart qualification questions',
      'Instant email and SMS follow-up',
      'CRM integration and updates',
      'Priority routing to sales team',
    ],
    tools: ['Zapier', 'Make.com', 'HubSpot', 'ActiveCampaign'],
    deliverables: [
      'Custom qualification workflow',
      'Lead scoring system',
      'Automated follow-up sequences',
      'CRM pipeline automation',
    ],
    image: 'https://images.unsplash.com/photo-1763718528755-4bca23f82ac3?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1ODB8MHwxfHNlYXJjaHwyfHxBSSUyMGRhc2hib2FyZHxlbnwwfHx8fDE3NjQxOTQ2MjR8MA&ixlib=rb-4.1.0&q=85',
    useCases: ['B2B lead qualification', 'E-commerce customer segmentation', 'Service business triage'],
  },
  {
    id: 'business-automation',
    icon: 'Workflow',
    title: 'Business Process Automations',
    shortDescription: 'Streamline scheduling, follow-ups, data entry, and routine tasks.',
    roi: 'Save 10-20 hours per week on manual administrative work',
    features: [
      'Automated appointment scheduling',
      'Follow-up email sequences',
      'CRM data synchronization',
      'Invoice and payment processing',
      'Document generation',
    ],
    tools: ['Zapier', 'Make.com', 'Airtable', 'Google Workspace'],
    deliverables: [
      'Custom workflow automations',
      'Integration setup',
      'Process documentation',
      'Team training materials',
    ],
    image: 'https://images.unsplash.com/photo-1761195696590-3490ea770aa1?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDQ2Mzl8MHwxfHNlYXJjaHwyfHxhdXRvbWF0aW9uJTIwc3lzdGVtfGVufDB8fHx8MTc2NDIxNDMzMHww&ixlib=rb-4.1.0&q=85',
    useCases: ['Administrative task automation', 'Data entry elimination', 'Multi-platform syncing'],
  },
  {
    id: 'ai-content',
    icon: 'FileText',
    title: 'AI Content Systems',
    shortDescription: 'Automated social media, blog posts, and email content generation.',
    roi: 'Produce 10x more content in the same time',
    features: [
      'Automated social media posting',
      'Blog content generation',
      'Email campaign creation',
      'Content calendar management',
      'Brand voice training',
    ],
    tools: ['ChatGPT', 'Jasper', 'Buffer', 'Mailchimp'],
    deliverables: [
      'Content generation templates',
      'Publishing automation',
      'Content calendar system',
      'Brand voice guidelines',
    ],
    image: 'https://images.unsplash.com/photo-1762328862557-e0a36587cd3c?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2NjZ8MHwxfHNlYXJjaHwzfHxjaGF0Ym90JTIwaW50ZXJmYWNlfGVufDB8fHx8MTc2NDIxNDMyNXww&ixlib=rb-4.1.0&q=85',
    useCases: ['Social media automation', 'Blog content creation', 'Email marketing'],
  },
  {
    id: 'appointment-setter',
    icon: 'Calendar',
    title: 'Automated Appointment Setter System',
    shortDescription: 'End-to-end appointment booking with chatbot, SMS, email, and calendar sync.',
    roi: 'Book 40% more appointments with zero manual scheduling',
    features: [
      'AI-powered conversation flows',
      'Multi-channel booking (SMS, email, chat)',
      'Calendar synchronization',
      'Automatic reminders and confirmations',
      'No-show reduction workflows',
    ],
    tools: ['Calendly', 'ChatGPT', 'Twilio', 'Make.com'],
    deliverables: [
      'Full appointment booking system',
      'Multi-channel integration',
      'Reminder automation',
      'Analytics and reporting',
    ],
    image: 'https://images.unsplash.com/photo-1763718432504-7716caff6e99?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1ODB8MHwxfHNlYXJjaHwxfHxBSSUyMGRhc2hib2FyZHxlbnwwfHx8fDE3NjQxOTQ2MjR8MA&ixlib=rb-4.1.0&q=85',
    useCases: ['Coaching businesses', 'Real estate agents', 'Healthcare providers', 'Consultants'],
  },
  {
    id: 'crm-automation',
    icon: 'Database',
    title: 'CRM & Pipeline Automation',
    shortDescription: 'Automated contact tagging, lead scoring, and pipeline stage updates.',
    roi: 'Eliminate 90% of manual CRM data entry',
    features: [
      'Automatic contact enrichment',
      'Lead scoring and prioritization',
      'Stage progression automation',
      'Activity tracking and logging',
      'Custom field updates',
    ],
    tools: ['HubSpot', 'Pipedrive', 'GoHighLevel', 'Zapier'],
    deliverables: [
      'CRM workflow setup',
      'Automated tagging system',
      'Custom scoring models',
      'Pipeline automation rules',
    ],
    image: 'https://images.unsplash.com/photo-1763718528755-4bca23f82ac3?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1ODB8MHwxfHNlYXJjaHwyfHxBSSUyMGRhc2hib2FyZHxlbnwwfHx8fDE3NjQxOTQ2MjR8MA&ixlib=rb-4.1.0&q=85',
    useCases: ['Sales pipeline management', 'Lead nurturing automation', 'Customer journey tracking'],
  },
  {
    id: 'ai-sales-assistant',
    icon: 'Users',
    title: 'AI Sales Assistant',
    shortDescription: '24/7 AI that responds to leads, handles objections, and warms prospects.',
    roi: 'Respond to leads 10x faster and never miss an opportunity',
    features: [
      'Instant lead response (under 60 seconds)',
      'Objection handling and FAQ',
      'Qualification and discovery',
      'Meeting scheduling',
      'Human handoff when needed',
    ],
    tools: ['ChatGPT', 'Voiceflow', 'Twilio', 'HubSpot'],
    deliverables: [
      'AI sales assistant persona',
      'Conversation flow design',
      'CRM integration',
      'Performance dashboard',
    ],
    image: 'https://images.unsplash.com/photo-1762330470070-249e7c23c8c0?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2NjZ8MHwxfHNlYXJjaHwxfHxjaGF0Ym90JTIwaW50ZXJmYWNlfGVufDB8fHx8MTc2NDIxNDMyNXww&ixlib=rb-4.1.0&q=85',
    useCases: ['Inbound lead response', 'Sales qualification', '24/7 sales coverage'],
  },
];